#pragma once

#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#define SERVER_BASE_URL "http://YOUR_SERVER_API_HOST:12345"
#define DEVICE_ID "YOUR_GUIDE_CANE_DEVICE_ID"

#define BAIDU_CLIENT_ID "YOUR_BAIDU_API_CLIENT_ID"
#define BAIDU_CLIENT_SECRET "YOUR_BAIDU_API_CLIENT_SECRET"
#define BAIDU_CUID "YOUR_BAIDU_CUID"
