#pragma once

#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#define SERVER_BASE_URL "http://192.168.1.100:12345"

#define BAIDU_CLIENT_ID "YOUR_BAIDU_CLIENT_ID"
#define BAIDU_CLIENT_SECRET "YOUR_BAIDU_CLIENT_SECRET"
#define BAIDU_CUID "YOUR_BAIDU_CUID"
