#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include <Arduino.h>
#include "esp_camera.h"

#define CAMERA_WIFI_SSID "YOUR_HOTSPOT_SSID"
#define CAMERA_WIFI_PASSWORD "YOUR_HOTSPOT_PASSWORD"

#define CAMERA_HOSTNAME "esp32-cam"
#define CAMERA_FLASH_LED_PIN 4
#define CAMERA_STATUS_LED_PIN 33

#define CAMERA_PIXEL_FORMAT PIXFORMAT_JPEG
#define CAMERA_FRAME_SIZE FRAMESIZE_QVGA
#define CAMERA_JPEG_QUALITY 12
#define CAMERA_FB_COUNT 2

#endif
